[package]
name = "skyMap-back"
version = "0.1.0"
authors = ["fazerzinho <45016808+fazerzinho@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
